### ISSUE TITLE
[bug] get_params() no attribute 'classifier_head'

### ISSUE THREAD

**Issue by mglowacki100** [pmbaumgartner/setfit#3]
Hi,
Here is sample examle, run on google collab (I've also reproduced it on other env)
```
!pip install git+https://github.com/pmbaumgartner/setfit
```
```
from setfit import SetFitClassifier
docs = ["yay", "boo", "yes", "no", "yeah"]
labels = [1, 0, 1, 0, 1]

# takes a sentence-transformers model
clf = SetFitClassifier("paraphrase-MiniLM-L3-v2")
```
```
clf.get_params()
```
Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-6-b3ea3e5db17a>](https://localhost:8080/#) in <module>()
----> 1 clf.get_params()

[/usr/local/lib/python3.7/dist-packages/sklearn/base.py](https://localhost:8080/#) in get_params(self, deep)
    208         out = dict()
    209         for key in self._get_param_names():
--> 210             value = getattr(self, key)
    211             if deep and hasattr(value, "get_params"):
    212                 deep_items = value.get_params().items()

AttributeError: 'SetFitClassifier' object has no attribute 'classifier_head'
```
I've also tried to pass directly "LogisticRegression" in clf initializer but the same error. 
This error occurs also when you want to use setfit with GridSearchCV from sklearn, as it run get_params() behind the scenes.

**Comment by mglowacki100** [comment]
After some tweaking, I've noticed that also random_state is missing, but I think a way to fix it is in core.py:

```
class SetFitClassifier(BaseEstimator, ClassifierMixin):
    def __init__(
        self,
        model: str,
        classifier_head=LogisticRegression(),
        loss=losses.CosineSimilarityLoss,
        random_state: int = 1234,
    ):
        random.seed(random_state)
        np.random.seed(random_state)
        torch.manual_seed(random_state)
        self.random_state = random_state # NEW
        self.model = SentenceTransformer(model)
        self.classifier_head = classifier_head # WAS self.classifier = classifier_head
        self.loss = loss(self.model)
        self.fitted = False
   ....
```
Other way is to rename classfier_head to classifer in init method params.

**Comment by pmbaumgartner** [comment]
Thanks for the issue @mglowacki100 . I've got a PR created over here https://github.com/pmbaumgartner/setfit/pull/5. You can try out this branch with `pip install git+https://github.com/pmbaumgartner/setfit/tree/get-params-fix` I think. I'll merge that PR in a few days if I don't hear anything from you.

I've also added a test that just calls `get_params()` on the classifier. The issue was that scikit-learn expects all the parameter names in __init__ to be the same attributes on the object, so it got confused when I had an argument of `classifier_head` but called it `classifier` on the object.
